# Generated by Django 5.2.11 on 2026-02-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='status',
            field=models.CharField(default='processing', max_length=50),
        ),
    ]
